describe("Test example", function()
  it("Test can access vim namespace", function()
    assert.not_nil(vim, "Cannot access vim namespace")
  end)
  it("Test can useNvim Lua API", function()
    assert.are.same(vim.trim("  a "), "a")
  end)
  it("Test can access module in lua/example", function()
    assert.not_nil(require("example"), "Could not access main module")
  end)
end)
